// Generated by CoffeeScript 1.7.1
(function() {
  var commander, mms, pkg;

  commander = require('commander');

  pkg = require('../package.json');

  mms = require('./mms');

  commander.version(pkg.version).usage('[options] [command]').option('--ext <ext>', 'extension of migration files').option('--db <db>', 'connection of migration db').option('--dir <dir>', 'directory for saving migration files').option('--schema <schema>', 'the schema file to saving migration status');

  commander.command('migrate').usage('[name|version|step]').description('(default) migrate to the given migration').action(function(name, options) {
    if (arguments.length < 2) {
      options = name;
      name = null;
    }
    return mms.migrate(name, options.parent);
  });

  commander.command('rollback').usage('[name|version|step]').description('rollback till given migration').action(function(name, options) {
    if (arguments.length < 2) {
      options = name;
      name = '1';
    }
    return mms.rollback(name, options.parent);
  });

  commander.command('create').usage('[name]').description('create a new migration file with its name').action(function(name, options) {
    if (arguments.length < 2) {
      return console.error('  fail'.red, "missing name".grey);
    }
    return mms.create(name, options.parent);
  });

  commander.command('status').description('show status of migrations').action(function(options) {
    return mms.status();
  });

  commander.parse(process.argv);

}).call(this);
