// Generated by CoffeeScript 1.7.1
(function() {
  var commander, mms, pkg, usage;

  pkg = require('../package.json');

  mms = require('./mms');

  commander = require('commander');

  usage = "\nUsage: mms [command]\n\nCommands:\n\n  migrate    [name|version|step]    migrate to the given migration (default)\n  rollback   [name|version|step]    rollback till given migration\n  create     [name]                 create a new migration file with its name\n";

  switch (process.argv[2]) {
    case '-h':
    case '--help':
      console.log(usage);
      break;
    case '-v':
    case '--version':
      console.log(pkg.name + " " + pkg.version);
      break;
    case 'migrate':
      mms.migrate(process.argv[3]);
      break;
    case 'rollback':
      mms.rollback(process.argv[3]);
      break;
    case 'create':
      mms.create(process.argv[3]);
      break;
    case void 0:
      mms.migrate();
      break;
    default:
      console.log("Unknown command " + process.argv[2]);
      console.log(usage);
  }

}).call(this);
