// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    dir: 'migrations',
    db: 'mongodb://127.0.0.1/test',
    file: 'migrations/.migrate.json',
    ext: '.js'
  };

}).call(this);
