// Generated by CoffeeScript 1.7.1
(function() {
  var Logger, logger;

  Logger = require('graceful-logger').Logger;

  logger = new Logger("  :0.cyan :1.grey");

  module.exports = logger;

}).call(this);
