// Generated by CoffeeScript 1.7.1
(function() {
  var MMS;

  MMS = (function() {
    function MMS() {}

    MMS.prototype.create = function(file, callback) {
      if (callback == null) {
        callback = function() {};
      }
    };

    MMS.prototype.migrate = function(name, callback) {
      if (callback == null) {
        callback = function() {};
      }
    };

    MMS.prototype.rollback = function(name, callback) {
      if (callback == null) {
        callback = function() {};
      }
    };

    return MMS;

  })();

  module.exports = new MMS;

}).call(this);
